User-Interface, Milestone 2
Azeem838/tic-tac-toe pull request #3
Opened 2020-05-11 13:44 UTC by Abdoulaye-Thespy

In this milestone, we created user interface for Tic-tac-toe.

2020-05-11 15:15 UTC, shshamim63 requested changes
## Status :vertical_traffic_light: Required Changes :tractor: 
___
Hi @Abdoulaye-Thespy and @Azeem838 :wave: 
An awesome initiative, but you need to cover some edge cases to get approval for this milestone. Lets get to them.
___
### :spades: Mandatory Changes :spades: 
___ 
1. Add the following message in your main.rb
- Informs the user if a move is invalid.
- informs player if there is a winner
- informs players if the game is drawn.
2. Reform the loop
3. Add a gemfile in the project's root directory.
4. Displays board after a user makes move.
___
#### Please fix the above-mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/)

2020-05-11 15:15 UTC, shshamim63 commented on bin/main.rb
> +require 'daru'
It seems that you are using the `daru` gem, to visualize and organize the data. But you don't have a Gemfile containing the `daru` gem. And that is why while I was trying to execute the `main.rb` it was giving me errors. So please create a Gemfile in your root folder by following this [link](https://stackoverflow.com/questions/30358612/how-to-create-a-gemfile). Instead of gem 'rspec' you will add gem 'daru', '~> 0.2.2'. After that add a simple instruction in your pull request description to run bundle install first.

2020-05-11 15:15 UTC, shshamim63 commented on bin/main.rb
> +end
The loop should not depend on a certain number, it should rely on the result (win / draw)  game_end. You can follow this, 
```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move
  
  if winner # and/or draw
    game_on = false
  end
end

```

2020-05-12 01:26 UTC, uryelah commented
Hello **Azeem Mahomed Ahmed & Abdoulaye Razak**, I'm Sarah, your reviewer for this PR 👩‍🚀  

You are doing a great job with this project! Picking the first user is a really nice feature you guys added.
 
You are still missing one requirement though, you got this! 🦾 

--------

## Changes Required 🏗️ 🐛 💡

- [ ] [REQUIRED] game informs player if the selected move is a winning move (currently you only have a print for a tie condition)

----

 **Kindly fix the pointed out issues before requesting the next code review**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-05-12 05:31 UTC, serdg0 approved these changes
**Congratulations** @Azeem838 & @Abdoulaye-Thespy  :fireworks: :100: :fireworks:
Feel free to merge.
Keep the outstanding work in your next project!
**Happy Coding!** :computer: :nerd_face:
**_Sergio Diaz_**

2020-05-12 07:50 UTC, merged